name: flutter_webview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  adaptive_dialog: ^1.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
